---

blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Deltares/117/GeoLab-Suite/discussions/
    about: Ask questions and discuss with other community members