[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "probabilistic-library"
dynamic = ["version"]
description = "Package which provides probabilistic methods"
license = "LGPL-3.0"
requires-python = ">=3.10"
dependencies = ["numpy", "matplotlib"]
authors = [
    { name = "Deltares", email = "software.support@deltares.nl" },
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[tool.hatch.version]
path = "probabilistic_library/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/probabilistic_library",
]

