name: docs

# build the documentation whenever there are new commits on main
on:
  workflow_dispatch:
  push:
    branches:
      - feature/PROBL-207-actions
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p tmp/wiki/
    
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: tmp/wiki
    
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # ADJUST THIS: install all dependencies (including pdoc)
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: pip install pdoc
      - run: pip install mermaid-python
      - run: pip install matplotlib
      - run: pdoc -o tmp/wiki/docs --mermaid ./sources/Deltares.Probabilistic.PWrapper/probabilistic_library

      - name: Push to wiki
        run: |
          cd tmp/wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: Added pdoc documents"
          git push      

      #- uses: actions/upload-pages-artifact@v4
      #  with:
      #    path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  permissions:
  #    pages: write
  #    id-token: write
  #  environment:
  #    name: github-pages
  #    url: ${{ steps.deployment.outputs.page_url }}
  #  steps:
  #    - id: deployment
  #      uses: actions/deploy-pages@v4

