name: docs2

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/PROB-207-docs-as-subpage

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      # 3️⃣ Install Poetry
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
        working-directory: sources/Deltares.Probabilistic.PWrapper

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Show current pyproject.toml
        run: cat sources/Deltares.Probabilistic.PWrapper/pyproject.toml


      # 4️⃣ Install Python dependencies
      - name: Install Python dependencies
        run: poetry install
        working-directory: sources/Deltares.Probabilistic.PWrapper

      # 5️⃣ Set up Node.js for Mermaid CLI
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 6️⃣ Install Mermaid CLI globally
      - run: npm install -g @mermaid-js/mermaid-cli

      # 7️⃣ Build Sphinx documentation
      - name: Build Sphinx docs
        run: poetry run sphinx-build -b html -a -E docs docs/build/html

      # 8️⃣ Upload HTML docs as artifact for GitHub Pages
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
